select * from INDIVIDUAL_DIET_RECORD_FOOD_NUTRIENT;
DELETE FROM INDIVIDUAL_DIET_RECORD_FOOD_NUTRIENT;
commit;

ALTER TABLE INDIVIDUAL_DIET_RECORD_FOOD_NUTRIENT MODIFY (FOOD_NAME VARCHAR2(200));
ALTER TABLE INDIVIDUAL_DIET_RECORD_FOOD_NUTRIENT MODIFY (food_size VARCHAR2(50));
ALTER TABLE INDIVIDUAL_DIET_RECORD_FOOD_NUTRIENT MODIFY (NUT_CON_STR_QUA VARCHAR2(50));

