-- 시퀀스 생성
CREATE SEQUENCE seq_qna_post_no START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_bulletin_post_no START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_announcement_post_no START WITH 1 INCREMENT BY 1 NOCACHE;


-- QnA 게시글 20개
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '운동 시작하는 분들을 위한 조언', '처음에는 가벼운 운동부터 시작하시는 것이 좋습니다...', 0, 5, 0, 10, SYSDATE, 'user1', 1);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '식단 조언이 필요합니다', '하루 3끼 식단을 어떻게 구성하면 좋을까요?', 0, 3, 0, 8, SYSDATE, 'user2', 2);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '헬스장 추천 부탁드립니다', '강남구 근처 헬스장 추천해주세요', 0, 2, 0, 15, SYSDATE, 'user3', 3);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '운동 시간 조언', '하루에 얼마나 운동하는 것이 좋을까요?', 0, 8, 0, 14, SYSDATE, 'mentor1', 1);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '식단 관리 어려움', '식단 관리가 너무 어려운데 도와주세요', 0, 4, 0, 9, SYSDATE, 'user4', 2);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '헬스장 PT 추천', 'PT 받아보고 싶은데 추천 부탁드립니다', 0, 6, 0, 11, SYSDATE, 'user1', 3);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '운동 기구 사용법', '운동 기구 사용법을 알려주세요', 0, 6, 0, 13, SYSDATE, 'user2', 1);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '식단 계산기 사용법', '식단 계산기 사용법을 알려주세요', 0, 3, 0, 7, SYSDATE, 'user3', 2);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '헬스장 이용 시간', '헬스장 이용 시간 추천해주세요', 0, 5, 0, 10, SYSDATE, 'mentor1', 3);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '운동 순서 조언', '운동 순서를 어떻게 정하면 좋을까요?', 0, 5, 0, 9, SYSDATE, 'user4', 1);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '식단 기록 방법', '식단을 어떻게 기록하면 좋을까요?', 0, 4, 0, 8, SYSDATE, 'user1', 2);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '헬스장 매니저 추천', '헬스장 매니저 추천 부탁드립니다', 0, 7, 0, 12, SYSDATE, 'user2', 3);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '운동 강도 조절', '운동 강도를 어떻게 조절하면 좋을까요?', 0, 8, 0, 14, SYSDATE, 'user3', 1);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '식단 영양소 계산', '식단의 영양소를 어떻게 계산하나요?', 0, 6, 0, 11, SYSDATE, 'mentor1', 2);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '헬스장 회원권', '헬스장 회원권 구매 시 주의사항이 있을까요?', 0, 4, 0, 7, SYSDATE, 'user4', 3);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '운동 효과 확인', '운동 효과를 어떻게 확인할 수 있을까요?', 0, 7, 0, 12, SYSDATE, 'user1', 1);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '식단 준비 시간', '식단 준비 시간을 어떻게 단축할 수 있을까요?', 0, 5, 0, 10, SYSDATE, 'user2', 2);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '헬스장 수업 추천', '헬스장 수업 추천 부탁드립니다', 0, 6, 0, 13, SYSDATE, 'user3', 3);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '운동 시작 전 준비', '운동 시작 전 준비사항이 궁금합니다', 0, 4, 0, 8, SYSDATE, 'mentor1', 1);
INSERT INTO qna_post (qna_post_no, qna_post_subject, qna_post_content, private_check, qna_post_recommend, qna_post_decommend, post_record_cnt, regdate, creator_id, qna_post_header_no) VALUES (seq_qna_post_no.NEXTVAL, '식단 변형 방법', '식단을 어떻게 변형하면 좋을까요?', 0, 5, 0, 9, SYSDATE, 'user4', 2);

select * from qna_post;

-- 자유게시판 20개
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '오늘 운동 후기', '오늘 운동 정말 좋았어요!', 0, 10, 0, 20, SYSDATE, 'user1', 1);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '식단 공유합니다', '오늘의 식단을 공유합니다', 0, 8, 0, 15, SYSDATE, 'user2', 2);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '헬스장 후기', '새로 가입한 헬스장 후기입니다', 0, 12, 0, 25, SYSDATE, 'user3', 3);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '운동 성과 공유', '3개월 운동 후 성과를 공유합니다', 0, 15, 0, 30, SYSDATE, 'mentor1', 4);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '식단 레시피', '건강식 레시피 공유합니다', 0, 9, 0, 18, SYSDATE, 'user4', 2);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '헬스장 추천', '좋은 헬스장 추천드립니다', 0, 11, 0, 22, SYSDATE, 'user1', 3);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '운동 루틴', '제 운동 루틴을 공유합니다', 0, 13, 0, 28, SYSDATE, 'user2', 1);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '식단 준비 팁', '식단 준비 팁을 공유합니다', 0, 7, 0, 14, SYSDATE, 'user3', 2);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '헬스장 기구', '헬스장 기구 사용법을 공유합니다', 0, 10, 0, 20, SYSDATE, 'mentor1', 3);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '운동 동기부여', '운동 동기부여 방법을 공유합니다', 0, 12, 0, 25, SYSDATE, 'user4', 1);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '식단 기록', '식단 기록 방법을 공유합니다', 0, 8, 0, 16, SYSDATE, 'user1', 2);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '헬스장 수업', '헬스장 수업 후기를 공유합니다', 0, 11, 0, 23, SYSDATE, 'user2', 3);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '운동 효과', '운동 효과를 공유합니다', 0, 14, 0, 29, SYSDATE, 'user3', 4);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '식단 영양소', '식단 영양소 계산법을 공유합니다', 0, 9, 0, 17, SYSDATE, 'mentor1', 2);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '헬스장 시설', '헬스장 시설 후기를 공유합니다', 0, 10, 0, 21, SYSDATE, 'user4', 3);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '운동 기구', '운동 기구 사용 후기를 공유합니다', 0, 13, 0, 27, SYSDATE, 'user1', 1);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '식단 준비', '식단 준비 방법을 공유합니다', 0, 7, 0, 13, SYSDATE, 'user2', 2);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '헬스장 환경', '헬스장 환경 후기를 공유합니다', 0, 11, 0, 24, SYSDATE, 'user3', 3);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '운동 성공', '운동 성공 후기를 공유합니다', 0, 15, 0, 31, SYSDATE, 'mentor1', 4);
INSERT INTO bulletin_post (bulletin_post_no, bulletin_post_subject, bulletin_post_content, private_check, bulletin_post_recommend, bulletin_post_decommend, post_record_cnt, regdate, creator_id, bulletin_post_header_no) VALUES (seq_bulletin_post_no.NEXTVAL, '식단 성공', '식단 성공 후기를 공유합니다', 0, 10, 0, 19, SYSDATE, 'user4', 2);

select * from bulletin_post;

-- 공지사항
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '시스템 점검 안내', '2024년 3월 1일 새벽 2시부터 4시까지 시스템 점검이 있을 예정입니다.', 0, 0, 0, 50, SYSDATE, 'admin1', 1);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '신규 회원 이벤트', '신규 회원 가입 시 1개월 무료 이용권을 드립니다!', 0, 0, 0, 45, SYSDATE, 'admin1', 2);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '서비스 이용 안내', '서비스 이용 시 주의사항을 안내드립니다.', 0, 0, 0, 40, SYSDATE, 'admin1', 3);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '개인정보 처리방침 변경', '개인정보 처리방침이 변경되었습니다.', 0, 0, 0, 35, SYSDATE, 'admin1', 1);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '이용약관 개정', '이용약관이 개정되었습니다.', 0, 0, 0, 30, SYSDATE, 'admin1', 1);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '신규 기능 안내', '새로운 기능이 추가되었습니다.', 0, 0, 0, 25, SYSDATE, 'admin1', 2);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '서비스 이용 제한 안내', '부적절한 이용으로 인한 제한 안내입니다.', 0, 0, 0, 20, SYSDATE, 'admin1', 3);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '휴면 계정 안내', '장기 미이용 계정 휴면 전환 안내입니다.', 0, 0, 0, 15, SYSDATE, 'admin1', 1);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '이벤트 당첨자 발표', '2월 이벤트 당첨자 명단입니다.', 0, 0, 0, 40, SYSDATE, 'admin1', 2);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '서비스 이용 규칙', '서비스 이용 시 준수해야 할 규칙입니다.', 0, 0, 0, 35, SYSDATE, 'admin1', 3);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '개인정보 유출 방지', '개인정보 유출 방지를 위한 안내입니다.', 0, 0, 0, 30, SYSDATE, 'admin1', 1);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '이벤트 참여 안내', '3월 이벤트 참여 방법 안내입니다.', 0, 0, 0, 25, SYSDATE, 'admin1', 2);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '서비스 이용 제한', '부적절한 이용으로 인한 제한 안내입니다.', 0, 0, 0, 20, SYSDATE, 'admin1', 3);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '휴면 계정 전환', '장기 미이용 계정 휴면 전환 안내입니다.', 0, 0, 0, 15, SYSDATE, 'admin1', 1);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '이벤트 당첨', '1월 이벤트 당첨자 명단입니다.', 0, 0, 0, 40, SYSDATE, 'admin1', 2);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '서비스 이용 규칙 변경', '서비스 이용 규칙이 변경되었습니다.', 0, 0, 0, 35, SYSDATE, 'admin1', 3);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '개인정보 보호', '개인정보 보호를 위한 안내입니다.', 0, 0, 0, 30, SYSDATE, 'admin1', 1);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '이벤트 참여 방법', '4월 이벤트 참여 방법 안내입니다.', 0, 0, 0, 25, SYSDATE, 'admin1', 2);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '서비스 이용 제한 해제', '이용 제한 해제 안내입니다.', 0, 0, 0, 20, SYSDATE, 'admin1', 3);
INSERT INTO announcement_post (announcement_post_no, announcement_post_subject, announcement_post_content, private_check, announcement_post_recommend, announcement_post_decommend, post_record_cnt, regdate, creator_id, announcement_post_header_no) VALUES (seq_announcement_post_no.NEXTVAL, '휴면 계정 해제', '휴면 계정 해제 방법 안내입니다.', 0, 0, 0, 15, SYSDATE, 'admin1', 1);

select * from bulletin_post;